import OpenAI from 'openai';
import { NextResponse } from 'next/server';

const SYSTEM_PROMPT_IT =
  'Sei un copywriter esperto e delicato per un\'agenzia funebre. Il tuo compito e scrivere un necrologio breve (massimo 4-5 frasi), commovente, elegante e rispettoso. Devi integrare i tratti caratteristici forniti dall\'utente in modo naturale e grammaticalmente perfetto, senza sembrare artificiale.';

const SYSTEM_PROMPT_EN =
  'You are an expert and delicate copywriter for a funeral agency. Your task is to write a short obituary (maximum 4-5 sentences), moving, elegant and respectful. Integrate the user\'s traits naturally with grammatically correct language and avoid artificial phrasing. Reply only in English.';

export async function POST(request) {
  try {
    if (!process.env.OPENAI_API_KEY) {
      return NextResponse.json({ error: 'OPENAI_API_KEY not configured on server.' }, { status: 500 });
    }

    const body = await request.json();
    const name = (body?.name ?? '').toString().trim();
    const traits = (body?.traits ?? '').toString().trim();
    const language = (body?.language ?? '').toString().toLowerCase() === 'en' ? 'en' : 'it';

    if (!name) {
      return NextResponse.json(
        { error: language === 'en' ? 'Name is required.' : 'Il nome del defunto e obbligatorio.' },
        { status: 400 }
      );
    }

    const userPrompt =
      language === 'en'
        ? `Deceased name: ${name}\nKey traits: ${traits || 'Not specified.'}`
        : `Nome del defunto: ${name}\nTratti caratteristici: ${traits || 'Non specificati.'}`;

    const client = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY
    });

    const response = await client.responses.create({
      model: 'gpt-4o-mini',
      input: [
        { role: 'system', content: language === 'en' ? SYSTEM_PROMPT_EN : SYSTEM_PROMPT_IT },
        { role: 'user', content: userPrompt }
      ]
    });

    const text = response.output_text?.trim();

    if (!text) {
      return NextResponse.json(
        { error: language === 'en' ? 'No text generated by model.' : 'Nessun testo generato dal modello.' },
        { status: 502 }
      );
    }

    return NextResponse.json({ text });
  } catch (error) {
    console.error('generate-obituary error:', error);
    return NextResponse.json(
      { error: 'Error while generating obituary.' },
      { status: 500 }
    );
  }
}
